### ISSUE TITLE
Not rendering at all

### ISSUE THREAD

**Issue by EmeraldSpecter** [silentjames/WoD-charsheets-for-Obsidian#6]
<img width="1292" alt="Screenshot 2024-09-12 at 10 59 39 AM" src="https://github.com/user-attachments/assets/18a3de7b-b7d1-4c0e-9b6a-82d759f31d6f">

I've got the code to my js file linked and the error I am receiving is above. It isn't rendering the sheet at all. Any ideas?

**Comment by silentjames** [comment]
@EmeraldSpecter hello!
I also see this message from time to time, and don't know how to fix it =\
I suppose it happens because the script starts running before the statblock is finally rendered, so the script can't get class name.

The JS script in the beginning has line like 
`sleep(160).then(() => {` 
 
 That's suppose to be a delay before the script starts running - and I'm trying to find a perfect timing between the moment when the statblock is loaded and when the script starts.
 
 You can try to increase this number (160 is in milliseconds) and check what's going on!
